---
services:
  guacd:
    image: guacamole/guacd
    container_name: some-guacd
    networks:
      - guacnet # May need to create this manually
  guacamole:
    image: guacamole/guacamole
    container_name: some-guacamole
    networks:
      - guacnet
    ports:
      - "8080:8080"
    depends_on:
      - guacd
networks:
  guacnet:
    driver: bridge
