# Generated by Django 5.2.3 on 2025-06-25 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSegments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.UUID('48aa7e2d-12c4-4467-b9ae-d2a6b9987727'), max_length=255, unique=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('segment_type', models.CharField(choices=[('productive', 'productive'), ('non-productive', 'non-productive'), ('neutral', 'neutral'), ('away', 'away'), ('idle', 'idle')], max_length=255)),
            ],
            options={
                'db_table': 'time_segments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrackerAppCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.UUID('606ef7c1-26cd-4a74-b460-10940b2e46bd'), max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('productivity_status_type', models.CharField(choices=[('productive', 'productive'), ('non-productive', 'non-productive'), ('neutral', 'neutral')], default='neutral', max_length=255)),
            ],
            options={
                'db_table': 'tracker_app_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organization_id', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('activation_confirm', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrackerApps',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.UUID('8d77c11b-e52d-435f-9c90-ee357336ce33'), max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='tracker.trackerappcategories')),
            ],
            options={
                'db_table': 'tracker_apps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrackerSummaries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_id', models.CharField(default=uuid.UUID('0a2c0b29-3807-4908-820c-7716e594f2d6'), max_length=255, unique=True)),
                ('summary_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('last_seen_time', models.TimeField()),
                ('working_time', models.IntegerField()),
                ('productive_time', models.IntegerField()),
                ('non_productive_time', models.IntegerField()),
                ('away_time', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.users')),
            ],
            options={
                'db_table': 'tracker_summaries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.UUID('221752b4-7e37-4ff4-97aa-2c8c06650e9e'), max_length=255, unique=True)),
                ('capture_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.users')),
            ],
            options={
                'db_table': 'screenshots',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_id', models.CharField(default=uuid.UUID('fae442b0-c8db-46db-b638-9edeb2e713db'), max_length=255, unique=True)),
                ('window_title', models.TextField()),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('duration', models.IntegerField(db_comment='Measured in seconds')),
                ('is_active', models.BooleanField()),
                ('productivity_status', models.CharField(choices=[('productive', 'productive'), ('non-productive', 'non-productive'), ('neutral', 'neutral')], max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.trackerappcategories')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.trackerapps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.users')),
            ],
            options={
                'db_table': 'activity_logs',
                'managed': True,
            },
        ),
    ]
