# Generated by Django 5.2.3 on 2025-06-26 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSegments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('segment_type', models.CharField(choices=[('productive', 'productive'), ('non-productive', 'non-productive'), ('neutral', 'neutral'), ('away', 'away'), ('idle', 'idle')], max_length=255)),
            ],
            options={
                'db_table': 'time_segments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrackerAppCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('productivity_status_type', models.CharField(choices=[('productive', 'productive'), ('non-productive', 'non-productive'), ('neutral', 'neutral')], default='neutral', max_length=255)),
            ],
            options={
                'db_table': 'tracker_app_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activation_confirm', models.IntegerField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('capture_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'screenshots',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrackerApps',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='tracker.trackerappcategories')),
            ],
            options={
                'db_table': 'tracker_apps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('window_title', models.TextField()),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('duration', models.IntegerField(db_comment='Measured in seconds')),
                ('is_active', models.BooleanField()),
                ('productivity_status', models.CharField(choices=[('productive', 'productive'), ('non-productive', 'non-productive'), ('neutral', 'neutral')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.trackerappcategories')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.trackerapps')),
            ],
            options={
                'db_table': 'activity_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrackerSummaries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('summary_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('last_seen_time', models.TimeField()),
                ('working_time', models.IntegerField()),
                ('productive_time', models.IntegerField()),
                ('non_productive_time', models.IntegerField()),
                ('away_time', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_summaries',
                'managed': True,
            },
        ),
    ]
