# Generated by Django 4.1.13 on 2025-07-22 04:59

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackerActivity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tracker_activity_id", models.CharField(max_length=255)),
                ("tracker_id", models.CharField(max_length=255)),
                ("employee_id", models.CharField(max_length=255)),
                ("screenshot", models.CharField(max_length=255)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("activity_level", models.FloatField(blank=True, null=True)),
                ("duration", models.FloatField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "tracker_activity",
                "ordering": ["id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TrackerToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("employee_id", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=255)),
                ("ip", models.CharField(blank=True, max_length=255, null=True)),
                ("device_id", models.CharField(max_length=255)),
                ("os", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "tracker_token",
                "ordering": ["id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ActivityLogs",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "log_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("window_title", models.TextField()),
                ("start_timestamp", models.DateTimeField()),
                ("end_timestamp", models.DateTimeField()),
                ("is_active", models.BooleanField()),
                ("duration", models.IntegerField()),
                (
                    "productivity_status",
                    models.CharField(
                        choices=[
                            ("productive", "productive"),
                            ("non-productive", "non-productive"),
                            ("neutral", "neutral"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TrackerAppCategories",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "productivity_status_type",
                    models.CharField(
                        choices=[
                            ("productive", "productive"),
                            ("non-productive", "non-productive"),
                            ("neutral", "neutral"),
                        ],
                        default="neutral",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "db_table": "tracker_app_categories",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TrackerSummaries",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "summary_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("summary_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("last_seen_time", models.TimeField()),
                ("working_time", models.IntegerField()),
                ("productive_time", models.IntegerField()),
                ("non_productive_time", models.IntegerField()),
                ("away_time", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tracker_summaries",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TrackerApps",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("actual_name", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apps",
                        to="tracker.trackerappcategories",
                    ),
                ),
            ],
            options={
                "db_table": "tracker_apps",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TimeSegments",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.IntegerField()),
                (
                    "segment_type",
                    models.CharField(
                        choices=[
                            ("productive", "productive"),
                            ("non-productive", "non-productive"),
                            ("neutral", "neutral"),
                            ("away", "away"),
                            ("idle", "idle"),
                        ],
                        default="neutral",
                        max_length=255,
                    ),
                ),
                (
                    "activity_log",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_segment",
                        to="tracker.activitylogs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "time_segments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Screenshots",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("capture_time", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "screenshots",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="activitylogs",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.trackerapps"
            ),
        ),
        migrations.AddField(
            model_name="activitylogs",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.trackerappcategories",
            ),
        ),
        migrations.AddField(
            model_name="activitylogs",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
