# Generated by Django 5.2.3 on 2025-07-10 05:10
# Migration Script Revised Manually
# Reference: https://stackoverflow.com/questions/29787853/django-migrations-add-field-with-default-as-function-of-model

from django.db import migrations, models


class Migration(migrations.Migration):
    def set_actual_name_defaults(apps, schema_editor):
        TrackerApps = apps.get_model("tracker", "TrackerApps")
        for app in TrackerApps.objects.all().iterator():
            app.actual_name = app.name
            app.save()

    def unset_actual_name(apps, schema_editor):
        pass

    dependencies = [
        ('tracker', '0002_timesegments_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerapps',
            name='actual_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(set_actual_name_defaults, unset_actual_name),
        migrations.AlterField(
            model_name="trackerapps",
            name="actual_name",
            field=models.CharField(max_length=255),
        )
    ]
