# Generated by Django 5.2.3 on 2025-07-02 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesegments',
            name='activity_log',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_segment', to='tracker.activitylogs'),
        ),
    ]
