"""Initial Commit

Revision ID: 4d950eb67510
Revises: 
Create Date: 2025-06-24 18:36:25.038389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d950eb67510'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_segments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.Enum('productive', 'non-productive', 'neutral', 'away', 'idle', name='time_segments_segment_type_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('tracker_app_categories',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('tracker_apps',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('remember_token', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activation_confirm', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('log_id', sa.String(length=255), nullable=False),
    sa.Column('window_title', sa.Text(), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False, comment='Measured in seconds'),
    sa.Column('app_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('productivity_status', sa.Enum('productive', 'non-productive', 'neutral', name='activity_logs_productivity_status_enum'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['tracker_apps.id'], name='fk_activity_logs_tracker_apps'),
    sa.ForeignKeyConstraint(['category_id'], ['tracker_app_categories.id'], name='fk_activity_logs_tracker_app_categories'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_tracker_summaries_users'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id')
    )
    op.create_table('screenshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('capture_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_screenshots_users'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('tracker_app_categories_mapping',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('app_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['tracker_apps.id'], name='fk_tracker_app_categories_mapping_tracker_apps'),
    sa.ForeignKeyConstraint(['category_id'], ['tracker_app_categories.id'], name='fk_tracker_app_categories_mapping_tracker_app_categories'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'category_id', name='uq_tracker_app_categories_mapping_app_id_category_id')
    )
    op.create_table('tracker_summaries',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('summary_id', sa.String(length=255), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('last_seen_time', sa.Time(), nullable=False),
    sa.Column('working_time', sa.Integer(), nullable=False),
    sa.Column('productive_time', sa.Integer(), nullable=False),
    sa.Column('non_productive_time', sa.Integer(), nullable=False),
    sa.Column('away_time', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_tracker_summaries_users'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summary_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker_summaries')
    op.drop_table('tracker_app_categories_mapping')
    op.drop_table('screenshots')
    op.drop_table('activity_logs')
    op.drop_table('users')
    op.drop_table('tracker_apps')
    op.drop_table('tracker_app_categories')
    op.drop_table('time_segments')

    op.execute("DROP TYPE time_segments_segment_type_enum")
    op.execute("DROP TYPE activity_logs_productivity_status_enum")

    # ### end Alembic commands ###
